version: '3.1'

services: 
  nginx:
    image: nginx:1.13.7
    container_name: nginx
    depends_on:
      - api
    volumes:
       - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - raptor-network
    ports:
      - '80:80'
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: raptor-api
    environment:
      - FLASK_APP=app.py
    expose:
      - "5000"
    networks:
      raptor-network:
        aliases:
          - raptor-api
    ports:
      - 5000:5000

networks:
  raptor-network: